info:
  contact: {}
  description: fiber-api is a basic api framework developed based on fiber
  title: api
  version: v1
paths:
  /v1/hello/world:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Test
      tags:
      - v1
swagger: "2.0"
